version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pg_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dbt_pg/seeds:/docker-entrypoint-initdb.d/seeds  # Path corrected for seeds folder
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes: # this will reflect all data from /seeds local machine
      - /Users/aleksandar/Documents/visual studio code/dbt_pg_venv_docker/dbt_pg/seeds
    restart: unless-stopped
  
  streamlit:
    container_name: container-streamlit
    image: python:3.9
    command: >
      bash -c "pip install streamlit psycopg2-binary matplotlib folium streamlit-folium && streamlit run /app/streamlit_app.py"
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pg_db
      POSTGRES_HOST: postgres
    restart: unless-stopped

volumes:
  postgres-data: